HH-90756 add takeDeepStrings option
hhru/babel-plugin-static-value-extractor pull request #14
Opened 2019-08-01 16:33 UTC by kshshe

Добавил возможность брать строки из статических свойств из вложенных объектов

2019-08-01 16:54 UTC, kshshe commented
И здесь вопрос – нужно ли мне менять версию плагина?

2019-08-01 17:11 UTC, AndreyGladkov commented
ну обсуждали 20 раз, зачем?  декомпозируем компоненты и нет этой проблемы.

2019-08-01 17:22 UTC, xnimorz commented
> И здесь вопрос – нужно ли мне менять версию плагина?

да, нужно будет поднять минорную версию (по semVer)

> ну обсуждали 20 раз, зачем? декомпозируем компоненты и нет этой проблемы.

По результатам обсуждения мы и завели `can touch this` таску. О преимуществах написал в слаке

2019-08-01 17:23 UTC, AndreyGladkov commented
ну ок, раз решили, да Никита верно говорит минорная версия аппается.

2019-08-02 07:11 UTC, AndreyGladkov commented on test/index.js
> +                    takeDeepStrings: DEEP_STRINGS_ENABLED_FOR.includes(caseName),
зачем пропс? всегда парсим deep. и все.

2019-08-02 07:14 UTC, kshshe commented on test/index.js
> +                    takeDeepStrings: DEEP_STRINGS_ENABLED_FOR.includes(caseName),
Я просто не стал рисковать другими применениями плагина, не знал, вдруг где-то это важно. Если точно ок, уберу, сделаю всегда

2019-08-02 07:19 UTC, AndreyGladkov commented on test/index.js
> +                    takeDeepStrings: DEEP_STRINGS_ENABLED_FOR.includes(caseName),
он используется только в xhh, не нужны условия) это точно.

2019-08-02 07:19 UTC, kshshe commented on test/index.js
> +                    takeDeepStrings: DEEP_STRINGS_ENABLED_FOR.includes(caseName),
Ок, уберу)

2019-08-02 07:59 UTC, xnimorz requested changes

2019-08-02 07:59 UTC, xnimorz commented on src/traverser.js
>          nodeStaticProps.reduce((arr, { value }) => {
Технически ты можешь getFinalNodeValues вызывать прям на статическом свойства, потому что код одинаковый

2019-08-02 08:18 UTC, AndreyGladkov approved these changes

2019-08-02 08:24 UTC, xnimorz approved these changes

2019-08-02 08:26 UTC, merged